### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jcubic** [levithomason/keyboard-key#5]
What license this package have? no info and no LICENSE file. you can add license directly from github using create file and naming it LICENSE after that you will be able to pick license.

Lot of JavaScript developers use MIT but LGPL will also be good.

**Comment by jcubic** [comment]
I see it on npm (it's MIT) but github repo also should include LICENSE file and it should be in README too. so no one will miss it.

**Comment by levithomason** [comment]
Added, thanks!
